Launch server
gd-harco/ft_IRC pull request #15
Opened 2024-02-06 21:28 UTC by grodriguez-fr

Transfer main function to the server class and split the function

2024-02-07 13:37 UTC, gd-harco requested changes
DOES not Compile

```Shell
@gd-harco ➜ /workspaces/ft_IRC (lauch_server) $ make 
make irc
make[1]: Entering directory '/workspaces/ft_IRC'
c++ -Wall -Wextra -Werror -std=c++98 -g3 -MMD -MP -I incs/ -c srcs/main.cpp -o .build/main.zizi
Creating -c srcs/main.cpp -o n c++ -Wall -Wextra -Werror -std=c++98 -g3 -MMD -MP -I incs/ -c srcs/channel.cpp -o .build/channel.zizi
Creating -c srcs/channel.cpp -o n c++ -Wall -Wextra -Werror -std=c++98 -g3 -MMD -MP -I incs/ -c srcs/client.cpp -o .build/client.zizi
Creating -c srcs/client.cpp -o n c++ -Wall -Wextra -Werror -std=c++98 -g3 -MMD -MP -I incs/ -c srcs/server.cpp -o .build/server.zizi
srcs/server.cpp: In member function ‘void Server::handleEvent(epoll_event)’:
srcs/server.cpp:51:33: error: no matching function for call to ‘Server::handleExistingConnection(epoll_event&)’
   51 |   handleExistingConnection(event);
      |                                 ^
In file included from srcs/server.cpp:1:
incs/server.hpp:43:8: note: candidate: ‘void Server::handleExistingConnection(epoll_event, int)’
   43 |   void handleExistingConnection(struct epoll_event event, int currFd);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
incs/server.hpp:43:8: note:   candidate expects 2 arguments, 1 provided
srcs/server.cpp: In member function ‘void Server::handleEventEpollin(epoll_event, int)’:
srcs/server.cpp:67:52: error: unused parameter ‘event’ [-Werror=unused-parameter]
   67 | void Server::handleEventEpollin(struct epoll_event event, int currFd)
      |                                 ~~~~~~~~~~~~~~~~~~~^~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:67: .build/server.zizi] Error 1
make[1]: Leaving directory '/workspaces/ft_IRC'
make: *** [Makefile:39: all] Error 2
```

2024-02-07 13:37 UTC, gd-harco commented
@grodriguez-fr pense a faire un merge de main dans ta branche avant de fix, histoire de prendre en compte les recentes modifications de code.

2024-02-07 16:55 UTC, grodriguez-fr commented
Ok d'accord je merge ce soir

2024-02-14 15:05 UTC, grodriguez-fr commented
J'ai merge le main dans cette branche

2024-02-14 15:29 UTC, gd-harco approved these changes

2024-02-14 15:29 UTC, merged